ISSUE-32 Allow callbacks in SmtpFuture
yahoo/smtp-client-nio pull request #40
Opened 2023-03-27 21:31 UTC by chibenwa

This allow avoiding blocking in calling code to unwrap the future
and access the inner value. This empowers reactive/asynchronous/actor
systems integrations.

I chose the callback approach instead of using CompletableFuture in
order to minimize code changes.

## Description

Adds callbacks to SmtpFuture

Similar to https://github.com/yahoo/imapnio/pull/118

## Motivation and Context

Needs to call SmtpFuture.get to do anything usefull with this library however it blocks and defeat any reactive/asynchronous/actor system use of this library.

## How Has This Been Tested?

Unit test. I will also ensure timely that this solves my original issue.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Major release (change is NOT backward compatible with prior release)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2023-03-29 22:08 UTC, fansu commented on core/src/main/java/com/yahoo/smtpnio/async/client/SmtpAsyncClient.java
> +    public SmtpFuture<SmtpAsyncCreateSessionResponse> createSession(@Nonnull final SmtpAsyncSessionData sessionData,
Revert this line and keep same Future signature for now. So this Pull Request will only has new callbacks features added with 100% backward compatibility.

2023-03-29 22:08 UTC, fansu requested changes
Please address one comment, otherwise looks good.

2023-03-29 23:31 UTC, chibenwa commented on core/src/main/java/com/yahoo/smtpnio/async/client/SmtpAsyncClient.java
> +    public SmtpFuture<SmtpAsyncCreateSessionResponse> createSession(@Nonnull final SmtpAsyncSessionData sessionData,
This would force async user to cast in their code

SmtpFuture is a subclass of future hence compatibility is not an issue.

Btw similar changes were accepted in imapnio...

2023-03-31 05:41 UTC, fansu approved these changes

2023-03-31 05:42 UTC, merged