Other c
yahoo/smtp-client-nio pull request #42
Opened 2023-04-02 07:23 UTC by chibenwa

Follow up of https://github.com/yahoo/smtp-client-nio/pull/1

## Description

Implement usefull SMTP commands to actually make something of that library.

This includes a rebase, a rework to not have a hard dependency on javax.mail exposed to the user, and a POC of writing smtp message as imput stream to avoid full in-memory representation.

Last commit needs to be polished

## Motivation and Context

I want a Netty based library to write efficient email sending for Apache James.

## How Has This Been Tested?

TODO: 

 - [ ] Use Dockerized fake smtp to validate content and commands (at least on my codde)

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Major release (change is NOT backward compatible with prior release)

Writing a stream requires a breaking change: we can no longer always rely on the SMTP command being represented as a single ByteBuf.

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes . (**WIP**)
- [ ] All new and existing tests passed. (**WIP**)

2023-04-02 16:10 UTC, chibenwa commented
Locally the coverage do not pass but this seems unrelated to my changes...

I also want to write automated tests against a dockerized SMTP server for DATA stream variation before calling it a day...

2023-04-05 10:41 UTC, chibenwa commented
```
    @Test
    void test(SMTPMessageSender messageSender, DockerMockSmtp dockerMockSmtp) throws Exception {
        final int numOfThreads = 4;
        final SmtpAsyncClient smtpClient = new SmtpAsyncClient(numOfThreads);

        // Use SSL?
        final boolean enableSsl = false;

        // This example defines a connection to smtp.example.com through port 465 over SSL
        final SmtpAsyncSessionData sessionData = SmtpAsyncSessionData.newBuilder(dockerMockSmtp.getIPAddress(), 25, enableSsl)
            .setSessionContext("client007") // optional parameter used as an ID for debugging purposes
            .setSniNames(null) // optional list of SNI names
            .setLocalAddress(null) // optional local address if present
            .build();


        // Session configurations such as timeouts
        final SmtpAsyncSessionConfig sessionConfig = new SmtpAsyncSessionConfig()
            .setConnectionTimeout(5000)
            .setReadTimeout(7000)
            .setEnableStarttls(false); // enable startTls option which is false by default

        // Asynchronous call to create a Future containing the session data
        final Future<SmtpAsyncCreateSessionResponse> sessionFuture = smtpClient.createSession(sessionData, sessionConfig, SmtpAsyncSession.DebugMode.DEBUG_OFF);

        // Gets the session data from the future. This operation will block only if future is not yet complete
        final SmtpAsyncCreateSessionResponse sessionResponse = sessionFuture.get();

        // The actual session that can be used to issue commands
        final SmtpAsyncSession session = sessionResponse.getSession();

        session.execute(new ExtendedHelloCommand("james.org")).get();
        session.execute(new MailCommand(FROM)).get();
        session.execute(new RecipientCommand(RECIPIENT)).get();
        String message = "FROM: " + FROM + "\r\n" +
            "subject: test\r\n" +
            "\r\n" +
            "content\r\n";
        session.execute(new DataStreamCommand(new ByteArrayInputStream(message.getBytes()))).get();
        session.execute(new QuitCommand()).get();

        awaitAtMostOneMinute
            .until(() -> dockerMockSmtp.getConfigurationClient().listMails()
                .stream()
                .findFirst(), m -> {
                m.ifPresent(mail -> {
                    System.out.println("Sender: " + mail.getEnvelope().getFrom());
                    System.out.println("RCPTs: " + mail.getEnvelope().getRecipients());
                    System.out.println("-------");
                    System.out.println(mail.getMessage());
                    System.out.println("-------");
                });
                return m.isPresent();
            })
            .get();
    }
```

Yields...

![Screenshot from 2023-04-05 17-41-33](https://user-images.githubusercontent.com/6928740/230057861-3e852cc7-6527-403e-906a-d732b83cbc2c.png)

2023-04-19 11:22 UTC, chibenwa commented
Hello mainteners.

Any feedback on this work?

This is hanging for two weeks!

2023-04-19 11:24 UTC, chibenwa commented
Cc @fansu

2023-04-19 18:45 UTC, fansu commented on core/src/main/java/com/yahoo/smtpnio/async/request/DataCommand.java
> +    public static DataCommand fromSmtpMessage(final SMTPMessage message) {
Just for my understanding, Is this function serves as backward compatible utility function to support SMTPMessage as input?

2023-04-19 18:50 UTC, fansu commented on core/src/main/java/com/yahoo/smtpnio/async/request/DataStreamCommand.java
> +    private byte[] toByteArray(final InputStream inputStream) throws IOException {
combine these 3 functions toByteArray, copy and copyLarge

2023-04-19 18:55 UTC, fansu commented on core/src/main/java/com/yahoo/smtpnio/async/request/DataCommand.java
> +            .writeBytes(SmtpClientConstants.CRLF.getBytes(StandardCharsets.US_ASCII))
Lets use CRLF_B everywhere in all commands instead of SmtpClientConstants.CRLF.getBytes(StandardCharsets.US_ASCII)

CRLF_B is defined in AbstractSmtpCommand.java

2023-04-19 22:07 UTC, fansu commented on core/src/main/java/com/yahoo/smtpnio/async/internal/SmtpAsyncSessionImpl.java
> +    private Supplier<ChannelPromise> writeFuture(final Channel channel) {
javadoc for this function

2023-04-19 22:12 UTC, fansu commented on core/src/main/java/com/yahoo/smtpnio/async/internal/SmtpAsyncSessionImpl.java
>                  curEntry.setState(SmtpCommandEntry.CommandState.RESPONSES_DONE);
remove this line 414 then, since you will override state again in the next line 415

2023-04-19 22:18 UTC, fansu requested changes
please check some comments

2023-04-20 01:32 UTC, chibenwa commented on core/src/main/java/com/yahoo/smtpnio/async/request/DataCommand.java
> +    public static DataCommand fromSmtpMessage(final SMTPMessage message) {
Yes

2023-04-21 07:59 UTC, chibenwa commented on core/src/main/java/com/yahoo/smtpnio/async/internal/SmtpAsyncSessionImpl.java
>                  curEntry.setState(SmtpCommandEntry.CommandState.RESPONSES_DONE);
Not my code but OK ^^

![Screenshot from 2023-04-21 14-58-10](https://user-images.githubusercontent.com/6928740/233578137-6593f60f-063a-48df-bcbc-3260409a8136.png)

2023-04-21 22:59 UTC, fansu commented on core/src/main/java/com/yahoo/smtpnio/async/request/DataStreamCommand.java
> +    private static final byte[] END_OF_INPUT = "\r\n.\r\n".getBytes(StandardCharsets.US_ASCII);
private static final byte[] END_OF_INPUT = { '\r', '\n', '.', '\r', '\n' };

with javadoc/comment also

2023-04-21 22:59 UTC, fansu commented
Overall looks ok.

2023-04-22 00:59 UTC, fansu commented on core/src/main/java/com/yahoo/smtpnio/async/request/DataStreamCommand.java
> +import java.nio.charset.StandardCharsets;
remove this import of StandardCharsets, UT is breaking.

2023-04-24 04:46 UTC, fansu approved these changes

2023-04-24 05:03 UTC, merged